using System.Runtime.Serialization;

namespace System.ComponentModel.DataAnnotations;

/// <summary>Represents the exception that occurs during validation of a data field when the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class is used.</summary>
[Serializable]
public class ValidationException : Exception
{
	private ValidationResult _validationResult;

	/// <summary>Gets the instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class that triggered this exception.</summary>
	/// <returns>An instance of the validation attribute type that triggered this exception.</returns>
	public ValidationAttribute ValidationAttribute { get; private set; }

	/// <summary>Gets the <see cref="P:System.ComponentModel.DataAnnotations.ValidationException.ValidationResult" /> instance that describes the validation error.</summary>
	/// <returns>The <see cref="P:System.ComponentModel.DataAnnotations.ValidationException.ValidationResult" /> instance that describes the validation error.</returns>
	public ValidationResult ValidationResult
	{
		get
		{
			if (_validationResult == null)
			{
				_validationResult = new ValidationResult(Message);
			}
			return _validationResult;
		}
	}

	/// <summary>Gets the value of the object that causes the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class to trigger this exception.</summary>
	/// <returns>The value of the object that caused the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class to trigger the validation error.</returns>
	public object Value { get; private set; }

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class by using a validation result, a validation attribute, and the value of the current exception.</summary>
	/// <param name="validationResult">The list of validation results.</param>
	/// <param name="validatingAttribute">The attribute that caused the current exception.</param>
	/// <param name="value">The value of the object that caused the attribute to trigger the validation error.</param>
	public ValidationException(ValidationResult validationResult, ValidationAttribute validatingAttribute, object value)
		: this(validationResult.ErrorMessage, validatingAttribute, value)
	{
		_validationResult = validationResult;
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message, a validation attribute, and the value of the current exception.</summary>
	/// <param name="errorMessage">The message that states the error.</param>
	/// <param name="validatingAttribute">The attribute that caused the current exception.</param>
	/// <param name="value">The value of the object that caused the attribute to trigger validation error.</param>
	public ValidationException(string errorMessage, ValidationAttribute validatingAttribute, object value)
		: base(errorMessage)
	{
		Value = value;
		ValidationAttribute = validatingAttribute;
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using an error message generated by the system.</summary>
	public ValidationException()
	{
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message.</summary>
	/// <param name="message">A specified message that states the error.</param>
	public ValidationException(string message)
		: base(message)
	{
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message and a collection of inner exception instances.</summary>
	/// <param name="message">The error message.</param>
	/// <param name="innerException">The collection of validation exceptions.</param>
	public ValidationException(string message, Exception innerException)
		: base(message, innerException)
	{
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using serialized data.</summary>
	/// <param name="info">The object that holds the serialized data.</param>
	/// <param name="context">Context information about the source or destination of the serialized object.</param>
	protected ValidationException(SerializationInfo info, StreamingContext context)
		: base(info, context)
	{
	}
}
